jobs:
  build:
    docker:
      - image: circleci/node:latest
    resource_class: medium
    steps:
      - checkout
      - run: echo "This is a build step"    # similar to "script" in GitLab

  test:
    docker:
      - image: circleci/node:latest
    resource_class: medium
    steps:
      - checkout
      - run: echo "This is a test step"

  integration:
    docker:
      - image: circleci/node:latest
    resource_class: medium
    steps:
      - checkout
      - run:
          command: |
            echo "This is an integration step"
            exit 1

  prod:
    docker:
      - image: circleci/node:latest
    resource_class: medium
    steps:
      - checkout
      - run: echo "This is a deploy step."
